dist: trusty
sudo: true
services:
- docker
language: node_js
node_js:
- '8.1'
install:
- npm install
before_script:
- DOCKER_IMAGE_NAME="q-coalition-calculation"
- DOCKER_TAG=$TRAVIS_BRANCH
script:
- npm run build
- npm test
- docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG
  nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
- if [ $TRAVIS_BRANCH == "staging" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
  docker run --rm -it -e RANCHER_URL -e CATTLE_ACCESS_KEY -e CATTLE_SECRET_KEY etlweather/gaucho
  upgrade $RANCHER_SERVICE_ID_STAGING --auto_complete --start_first --imageUuid="docker:nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG"
  || true; fi
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: fkfaAEC8nnGs0+UeYPiQYL9kFMZTskOzIu4+PzUfmevVBzgvA25id3wW8sDPhB0Qq39co1SutBzOWvTHAylVr+Vkkac3i8EbjyI6hbKgNolRTDV1Id6ltLLsZKnBzV0MRIowLzZ7CbaAQaV+DGfz8fchOV5awXXf4BhFZ2pgijJLlaq0UylF0+8RA86LmvXMGftx3U7ohj1ksMpYbADvdTjVYZfYaQSZsGvBD+FyI1CmUF6OfE2jXZVRL5opuSPQkZOgY1OPPzTPIIQTPHNtYsMtogoUn9ql5g7yQIKEFrOJFC/vhz9+TG8kz9qm6iOSriSfXoGDzShcQRF0AWq6L76ag8ESz/w0gr+q4AWim3oZ19cyOa6vHOyE1SPSLBFwEBM5u/MrZAOZ7iu28ilYYG+VCVr4TyigNRbwvsQKij3+KtvF7h5CDnToEGbMBFuhgiZTkV7kC3sdcyYIXs4xST6BH9shGAeYxTPrCLb/Gdsl2VFneaWQ1aAVw8D6y1LZRBp40ryPvflOrTuYzC7/6uQd93s4pAoDik7sqKat3pvFv0+reO1PsAbL/eJcUw6Rbb1v2c76/RJ1I7IjhESUsAAThqMrgtR4HSQXN2AYYyVIo6YSNj1WaF7ouKgaD5/sWddGD+lgL6MOUtAptl4u3I2mI5TA5ojsY/xZb8+xE68=
